name: projects_archiving
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# `flutter pub upgrade --major-versions`. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  shared_preferences: ^2.0.15
  dio: ^4.0.4
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  flutter_bloc: ^8.0.1
  url_launcher: ^6.1.2
  auto_route: ^4.0.1
  desktop_drop: ^0.3.3
  file_picker: ^4.5.1
  infinite_scroll_pagination:
    git:
      url: https://github.com/nicolashouriet/infinite_scroll_pagination.git
      ref: 5c753a6e0ad8eb3d826894b5b149b5f43e8325f4
  intl: ^0.17.0
  path: ^1.8.1
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  auto_route_generator: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/mobile.env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: notoKufi
      fonts:
        - asset: assets/fonts/NotoKufiArabic.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
